# Generated by Django 4.2.7 on 2023-11-07 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("event", "__first__"),
        ("advert", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advert",
            name="article_image",
        ),
        migrations.RemoveField(
            model_name="advert",
            name="content",
        ),
        migrations.RemoveField(
            model_name="advert",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="advert",
            name="title",
        ),
        migrations.AddField(
            model_name="advert",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adverts",
                to="event.event",
            ),
        ),
        migrations.AddField(
            model_name="advert",
            name="price",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="advert",
            name="seller_description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="advert",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
